@Manifest(
    name = "wip",
    label = "在制品管理",
    category = "生产运营管理",
    author = "JMAA",
    license = "LGPL v3",
    models = {
        WipBindCode.class,
        WipCode.class,
        WipDefect.class,
        WipModule.class,
        WipProcess.class,
        WipProcessQty.class,
        WipProduction.class,
        WipRepair.class,
        WipRoute.class,
        TraceCode.class,
        TraceDefect.class,
        TraceModule.class,
        TraceProcess.class,
        TraceProduction.class,
        TraceRepair.class,
        BatchCode.class,
        BatchRule.class,
        BatchCodeRule.class,
        BlockCode.class,
        Container.class,
        PrintRuleBatch.class,
        BatchCodePrintDialog.class,
        WipProductionMobile.class,
        TraceProductionMobile.class,
        ProductOrder.class,
        ProductOrderBom.class,
        ProductLabel.class,
        ProductLabelPrintDialog.class,
        WorkOrder.class,
        WorkOrderBom.class,
        WorkOrderProcessBom.class,
        WorkOrderRoute.class,
        WorkOrderRouteNode.class,
        ProductContainer.class,
        FeedingDialog.class,
        FeedingLog.class,
        FeedingMobile.class,
        MaterialReturn.class,
        MaterialReturnDialog.class,
        MaterialReturnMobile.class,
        WorkStationMaterial.class,
        WorkStationOnDuty.class,
        WorkStationOnDutyLog.class,
        WorkStationOnDutyDialog.class,
        UnloadDialog.class,
        ProductRoute.class,
        ResourceRoute.class,
        ResCompany.class,
        ResConfig.class,
        ProductStorageNotice.class,
        ProductStorageNoticeDetails.class,
        ProductStorageNoticeMobile.class,
    },
    demo = {
        "demo/wip.batch_rule.csv",
    },
    data = {
        "data/code_coding.xml",
        "data/print_template.xml",
        "views/menus.xml",
        "views/batch_code.xml",
        "views/batch_rule.xml",
        "views/block_code.xml",
        "views/container.xml",
        "views/wip_production.xml",
        "views/trace_production.xml",
        "views/wip_production_mobile.xml",
        "views/trace_production_mobile.xml",
        "views/work_order.xml",
        "views/product_order.xml",
        "views/work_station_material.xml",
        "views/work_station_on_duty.xml",
        "views/feeding_log.xml",
        "views/feeding_dialog.xml",
        "views/feeding_mobile.xml",
        "views/material_return.xml",
        "views/material_return_mobile.xml",
        "views/unload_dialog.xml",
        "views/product_route.xml",
        "views/company.xml",
    },
    depends = {
        "manufacturing",
        "md-product",
        "md-process-routing",
        "mfg-logistics",
        "label-manager"
    })
package jmaa.modules.wip;

import jmaa.modules.wip.models.*;
import org.jmaa.sdk.Manifest;
