#the port of the server
server.port=8066
#root path of source code
rootPath=D:/01-projects/jmaa/jmaa
#enviroment
env=\u5F00\u53D1\u73AF\u5883
#modules to update
forceUpdate=
#update permission when upgrade
updatePermission=true
#print sql to console
printSql=false
#load demo data
loadDemo=true
# LOCAL/MINIO
upload.config=local
upload.local.uploadPath=./data/files
#print client
print.client=D:/data/print
#log
logback.level=INFO
logback.plumelog=false
logback.plumelog.server=localhost:8891

spring.cloud.nacos.discovery.enabled=false

#xxlJob v2.1.2
xxl.job.admin.enable=false
#xxl.job.admin.address=http://localhost:8080/xxl-job-admin
xxl.job.admin.user_name=admin
xxl.job.admin.password=123456
xxl.job.admin.job_group=2
xxl.job.admin.executor.app_name=mom-job-dev
xxl.job.admin.executor.title=mom
xxl.job.admin.executor.ip=localhost
xxl.job.admin.executor.port=7988
xxl.job.admin.executor.log_path=/data/xxl-job
xxl.job.admin.executor.log_retention_days=30
