spring.profiles.active=${active_env:dev}
spring.application.name=jmaa
spring.main.banner-mode = off
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.location=/mnt/upload/
spring.main.allow-circular-references=true
druid.monitor.user=
druid.monitor.password=
druid.monitor.allow=
druid.monitor.deny=
license.company=jmaa
license.data=MoCOqAprRkXr1VE5dOKUGrG+pHkX6At8LgtEWorytgq88eIiStDpTPI33N/8UM1qc5pVpNLHvyBRbAhrl3fFWAFUcSgGR/hjyI6HOJgK/X1FakV7w1e9iSaBvRM663b3kTAtGLf4WRTIa3iKW+TBUzZr+xTvxVZKEU82vOi+f/UBCY4LtCkjPvmFiqZRhyXec3cS8jHClXoQtgfI6eHGIYZojsL/WTFcEsIg2fav6qckrJK74zoH6+wJbZfyr4bzx73W9j3Ns5/A5IFWTqRiwzpSjyNNt5O8jQd7P2HnMn972ReoAVL1s8y3E/ESVczyQxS4A/B9nfo3WjTscQUYew==
