#mysql
#driverClassName=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://localhost:3306/jmaa?serverTimezone=UTC&connectTimeout=60001&socketTimeout=60001
#username=root
#password=password

#driverClassName=org.h2.Driver
#url=jdbc:h2:file:./data/h2db;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#username=sa
#password=

driverClassName=org.postgresql.Driver
url=jdbc:postgresql://ballast.proxy.rlwy.net:51694/railway
username=<code|be62705c6a6489fb888af5880dbe91df5434945e6fa649bc3d3f3f5bdfea425c>
password=<code|f2c361f65255324c3cbfbda8908b973b30b8dd9bb99c045e5a75289fa9ae7dab49fe0c29c7591e9d>

initialSize=10
minIdle=10
maxActive=50
maxWait=60000
druid.filters=stat


