#mysql
#driverClassName=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://localhost:3306/jmaa?serverTimezone=UTC&connectTimeout=60001&socketTimeout=60001
#username=root
#password=password

#driverClassName=org.h2.Driver
#url=jdbc:h2:file:./data/h2db;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#username=sa
#password=

driverClassName=org.postgresql.Driver
url=jdbc:postgresql://ballast.proxy.rlwy.net:51694/railway
username=postgres
password=

initialSize=10
minIdle=10
maxActive=50
maxWait=60000
druid.filters=stat


