@Manifest(
    name = "base",
    label = "基础模块",
    author = "JMAA",
    license = "LGPL v3",
    category = "基础模块",
    models = {
        Unknown.class,
        IrAssets.class,
        IrAttachment.class,
        IrImport.class,
        IrLock.class,
        IrModuleCategory.class,
        IrModuleDependency.class,
        IrModule.class,
        IrModuleLog.class,
        IrModel.class,
        IrModelData.class,
        IrModelDataXmlLoader.class,
        IrModelDataCsvLoader.class,
        IrModelField.class,
        IrModelConstraint.class,
        IrModelFieldSelection.class,
        IrHttp.class,
        IrUiView.class,
        IrUiMenuBase.class,
        IrUiMenuMobile.class,
        IrUiMenu.class,
        IrUiState.class,
        ResCompany.class,
        ResLanguage.class,
        ResLocalization.class,
        ResConfig.class,
        RbacUser.class,
        RbacUserLog.class,
        RbacRole.class,
        RbacPermission.class,
        RbacSecurity.class,
        RbacToken.class,
        MixinCompany.class,
        MixinCompanies.class,
        RbacJwt.class,
        ResUpload.class,
        ResDownload.class,
    },
    demo = {
        "demo/rbac.user.csv",
        "demo/res.company.csv"
    },
    data = {
        "data/res_lang.xml",
        "data/rbac_data.xml",
        "data/res_download.xml",
        "views/web.xml",
        "views/pad.xml",
        "views/mobile.xml",
        "views/menus.xml",
        "views/ir_module.xml",
        "views/ir_model.xml",
        "views/ir_ui_menu.xml",
        "views/ir_ui_menu_mobile.xml",
        "views/ir_ui_view.xml",
        "views/ir_assets.xml",
        "views/res_config.xml",
        "views/res_lang.xml",
        "views/res_company.xml",
        "views/res_upload.xml",
        "views/res_download.xml",
        "views/rbac_views.xml",
    },
    autoInstall = true,
    application = false)
package org.jmaa.base;

import org.jmaa.base.models.*;
import org.jmaa.sdk.Manifest;
